Repository epodol/bsclibrary, pull requests merged in 2022-07, with the labels that each got.

#693 Create Account Page and Join Library Page
  common/package-lock.json
  common/package.json
  common/types/JoinRequest.d.ts
  common/types/User.d.ts
  firestore.rules
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  react/package-lock.json
  react/package.json
  react/src/components/LibraryNavigation/index.tsx
  react/src/components/Routing/HomeRouting.tsx
  react/src/components/Routing/LibraryRoutes.tsx
  react/src/components/Routing/index.tsx
  react/src/pages/CreateAccount/index.tsx
  react/src/pages/CustomPage/About/DueDates.tsx
  react/src/pages/CustomPage/About/Introduction.tsx
  react/src/pages/CustomPage/About/MissingBooks.tsx
  react/src/pages/CustomPage/About/Renewing.tsx
  react/src/pages/CustomPage/About/index.tsx
  react/src/pages/CustomPage/Contribute/Code.tsx
  react/src/pages/CustomPage/Contribute/Donate.tsx
  react/src/pages/CustomPage/Contribute/Volunteer.tsx
  react/src/pages/CustomPage/Contribute/index.tsx
  react/src/pages/JoinLibrary/index.tsx
  react/src/pages/LibraryHome/index.tsx
  react/src/pages/SignIn/index.tsx
  react/src/pages/Users/DisplayUser/UserInfo/index.tsx
  react/src/pages/Users/FindUser/index.tsx
Labels: enhancement, dependencies

#696 Add callNumber Field to Book
  common/types/Book.d.ts
  package-lock.json
  package.json
  react/package-lock.json
  react/package.json
  react/src/pages/Books/BooksTable/Book.tsx
  react/src/pages/Books/BooksTable/TableBody.tsx
  react/src/pages/Books/BooksTable/index.tsx
  react/src/pages/Books/DisplayBook/EditBook.tsx
  react/src/pages/Books/DisplayBook/ViewBook.tsx
Labels: enhancement

#699 Remove Algolia and Improve Book Search
  common/types/Book.d.ts
  functions/src/books/setBookCopiesData.ts
  react/.env.development
  react/.env.production
  react/.env.test
  react/package-lock.json
  react/package.json
  react/src/components/Footer/index.tsx
  react/src/index.css
  react/src/pages/Books/BooksTable/Book.tsx
  react/src/pages/Books/BooksTable/TableBody.tsx
  react/src/pages/Books/BooksTable/index.tsx
  react/src/pages/Books/DisplayBook/ViewBook.tsx
Labels: enhancement

#700 Add "Add Book" Menu
  common/types/Book.d.ts
  emulator-data/auth_export/accounts.json
  emulator-data/firebase-export-metadata.json
  emulator-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  emulator-data/firestore_export/all_namespaces/all_kinds/output-0
  emulator-data/firestore_export/firestore_export.overall_export_metadata
  emulator-data/storage_export/blobs/default-bucket%2Fbooks%2F
  emulator-data/storage_export/blobs/default-bucket%2Fusers%2F
  emulator-data/storage_export/buckets.json
  emulator-data/storage_export/metadata/default-bucket%2Fbooks%2F.json
  emulator-data/storage_export/metadata/default-bucket%2Fusers%2F.json
  firebase.json
  package-lock.json
  package.json
  react/package-lock.json
  react/package.json
  react/src/pages/Books/BooksTable/AddBook.tsx
  react/src/pages/Books/BooksTable/Book.tsx
  react/src/pages/Books/BooksTable/TableBody.tsx
  react/src/pages/Books/BooksTable/index.tsx
  react/src/pages/Books/DisplayBook/EditBook.tsx
  react/src/pages/Books/DisplayBook/ViewBook.tsx
  react/src/pages/Books/FeaturedBooks/index.tsx
Labels: enhancement

#701 Add Statistics
  common/types/statistics/Books.d.ts
  common/types/statistics/Checkouts.d.ts
  common/types/statistics/Copies.d.ts
  common/types/statistics/Users.d.ts
  emulator-data/auth_export/accounts.json
  emulator-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  emulator-data/firestore_export/all_namespaces/all_kinds/output-0
  emulator-data/firestore_export/firestore_export.overall_export_metadata
  functions/src/books/booksStatistics.ts
  functions/src/books/copiesStatistics.ts
  functions/src/books/setBookCopiesData.ts
  functions/src/checkouts/checkinBook.ts
  functions/src/checkouts/checkoutBook.ts
  functions/src/index.ts
  functions/src/users/userStatistics.ts
  react/src/pages/Books/DisplayBook/CopiesTable.tsx
  react/src/pages/CheckIn/index.tsx
  react/src/pages/CheckOut/index.tsx
Labels: enhancement

#708 Fix Light/Dark Mode icons to be standard icons
  react/src/components/LibraryNavigation/index.tsx
Labels: bug
